import type { Metadata } from "next";

import "bootstrap/dist/css/bootstrap-grid.min.css";
import BootstrapClient from "./components/BootstrapClient.js";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Chris's Contact Form",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <BootstrapClient />
      </body>
    </html>
  );
}
